-- FOOD_PRODUCT와 FOOD_ORDER 테이블에서 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회
SELECT B.PRODUCT_ID AS PRODUCT_ID, PRODUCT_NAME, SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A
INNER JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE DATE(B.PRODUCE_DATE) LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC,PRODUCT_ID ASC;

-- join과 inner join은 같은 의미