--SELECT * FROM FOOD_PRODUCT WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);
SELECT * FROM FOOD_PRODUCT ORDER BY PRICE DESC LIMIT 1;

--SELECT PRODUCT_ID, PRODUCT_NAME , .. MAX(PRICE) AS PRICE FROM FOOD_PRODUCT 가 안되는 이유
-- 조회를 하는 기준이 PRICE가 아니기에 MAX(PRICE)인 PRICE을 조회하고 나머지는 MAX(PRICE)와는 연관 없는 열이 출력된다.(구문자체가 오류)

