-- 3개의 테이블에서 22/4/13일 취소되지 않은 흉부외과(cs) 진료예약 내역을 조회
-- 진료예약번호, 환자이름, 환자번호, 진료과코드, 의사이름, 진료예약일시 항목이 출력 + 진료예약일시 기준 오름차순
SELECT AP.APNT_NO, PT.PT_NAME, PT.PT_NO, AP.MCDP_CD, DR.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP
JOIN PATIENT PT ON PT.PT_NO = AP.PT_NO
JOIN DOCTOR DR ON DR.MCDP_CD = AP.MCDP_CD AND DR.DR_ID = AP.MDDR_ID
WHERE AP.APNT_CNCL_YMD IS NULL
AND DATE(AP.APNT_YMD) = '2022-04-13'
AND AP.MCDP_CD = 'CS'
ORDER BY AP.APNT_YMD ASC;